[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.29"

remappings = [
    "@uniswap/v2-core/=src/core/",
    "@uniswap/lib/=src/libraries/",
    "@uniswap/v2-periphery/=src/periphery/",
    "forge-std/=lib/forge-std/src/"
]

# Add optimizer settings to reduce contract size
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
